### ISSUE TITLE
你好，请问你的电脑使用这个efi睡眠有没有问题呀？今天换上这个efi发现没办法正常睡眠，机箱风扇一直亮着的

### ISSUE THREAD

**Issue by Peach-H** [chenfeicqq/ASRock-B460M-ITX-ac-Hackintosh#5]

**Comment by chenfeicqq** [comment]
有同样的问题，风扇一直亮着的。

**Comment by chenfeicqq** [comment]
![image](https://user-images.githubusercontent.com/2122266/128632332-a3ad616f-14e6-4b38-b422-249e3cc2e879.png)

EFI用的是 iMac 设备，hibernatemode 的值默认应该为 0。

你可以用 Hackintool 工具检查下“电源”配置是否有问题，如果配置提示是红色的，修复下应该问题就解决了。

**Comment by Peach-H** [comment]
风扇问题解决了，但是现在睡眠了就无法唤醒，请问你有没有这个问题？

**Comment by Peach-H** [comment]
唤醒问题解决了，把启动项boot-args的代码换成keepsyms=1 darkwake=0 slide=1 igfxonln=1 vsmcgen=1 alcid=12即可正常睡眠和唤醒，顺便把开机第一段的图标改小了，开机日志取消了
